/**
 * Orders — mirrors `db/migrations/0006_orders.sql`, plus `order_state_transitions`
 * from `0010_immutability_and_guards.sql`.
 *
 * The order is the contract between a customer and a shop, and four decisions in
 * the SQL defend it. They are worth knowing before you write a query here:
 *
 *   • **The price is a snapshot.** Every agreed amount is copied onto the order at
 *     placement and then frozen by trigger. A change to a price list, a commission
 *     rate or a tax rate cannot alter a placed order (PRD §F inv. 6, FR-320).
 *   • **The money adds up, by constraint.** `total = subtotal - discount + surcharge
 *     + platformFee + tax`, and `shopPayable + commission + commissionTax +
 *     platformFee = total`. Unassigned money is unrepresentable (PRD §38.4).
 *   • **State changes are events.** `orderEvents` is append-only with a per-order
 *     monotonic `sequence`, so it is at once the audit trail, the customer timeline
 *     and the durable SSE outbox replayed after a reconnect (FR-410, NFR-16).
 *   • **The pickup code is a secret.** Only a keyed hash is stored for comparison;
 *     the displayable copy is encrypted. Reading the database does not let you
 *     collect someone else's documents (FR-425, NFR-14).
 */

import {
  boolean,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  smallint,
  text,
  uuid,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core'

import { bigintCount, createdAt, geographyPoint, id, paise, timestamps, tstz } from '../columns'
import { orderStateEnum, paymentStateEnum, userRoleEnum } from './enums'
import { serviceItems } from './catalogue'
import { files } from './files'
import { users } from './identity'
import { shops } from './shops'

/**
 * The authoritative order state machine, as data.
 *
 * Read twice for different purposes: the domain layer asks whether *this actor* may
 * make *this move*, and the `orders_guard_state_transition` trigger asks whether the
 * move exists at all. Terminal states simply have no outgoing rows, and admin
 * overrides are explicit rows rather than a wildcard — so no SQL path, including a
 * hand-written admin fix, can teleport an order into `collected`.
 */
export const orderStateTransitions = pgTable(
  'order_state_transitions',
  {
    fromState: orderStateEnum('from_state').notNull(),
    toState: orderStateEnum('to_state').notNull(),
    /** Who may make this move: 'customer' | 'shop' | 'admin' | 'system' | 'provider'. */
    actorTypes: text('actor_types')
      .array()
      .$type<('customer' | 'shop' | 'admin' | 'system' | 'provider')[]>()
      .notNull(),
    /** Whether the domain layer must record a reason on the resulting event. */
    requiresReason: boolean('requires_reason').notNull().default(false),
    note: text('note').notNull(),
  },
  (t) => [primaryKey({ columns: [t.fromState, t.toState] })],
)

export const orders = pgTable('orders', {
  id: id(),
  /** Human-quotable: CHP-7K2M-9QX4. Crockford base32, no ambiguous characters. */
  orderNumber: text('order_number').notNull(),
  customerUserId: uuid('customer_user_id')
    .notNull()
    .references(() => users.id),
  shopId: uuid('shop_id')
    .notNull()
    .references(() => shops.id),

  state: orderStateEnum('state').notNull().default('draft'),
  previousState: orderStateEnum('previous_state'),
  stateChangedAt: tstz('state_changed_at').notNull().defaultNow(),
  /** Monotonic counter for orderEvents, incremented under the state machine's row lock. */
  eventSequence: bigintCount('event_sequence').notNull().default(0n),
  /** Optimistic-concurrency token, so two dashboard tabs cannot both accept (FR-403). */
  version: integer('version').notNull().default(1),

  /** Generated by the client before the first placement attempt and resent on retry. */
  clientRequestId: text('client_request_id'),

  /** What the customer saw when they chose this shop, kept accurate after a rename. */
  shopNameSnapshot: text('shop_name_snapshot').notNull(),
  shopAddressSnapshot: text('shop_address_snapshot').notNull(),
  shopPhoneMaskedSnapshot: text('shop_phone_masked_snapshot'),
  shopLocationSnapshot: geographyPoint('shop_location_snapshot'),
  /** For "you're 400 m away" and analytics. Never for billing. */
  distanceMAtOrder: integer('distance_m_at_order'),

  fileCount: integer('file_count').notNull().default(0),
  totalPages: integer('total_pages').notNull().default(0),
  totalSheets: integer('total_sheets').notNull().default(0),
  copies: integer('copies').notNull().default(1),
  /** Queue-card summary: 'A4 · B&W · 2-sided · 3 copies'. */
  jobSummary: text('job_summary'),

  currency: text('currency').notNull().default('INR'),
  itemsSubtotalPaise: paise('items_subtotal_paise').notNull().default(0n),
  discountPaise: paise('discount_paise').notNull().default(0n),
  surchargePaise: paise('surcharge_paise').notNull().default(0n),
  /** ₹0 in the launch fee model; the column exists so adding one is config, not migration. */
  platformFeePaise: paise('platform_fee_paise').notNull().default(0n),
  /** GST the shop charges on the print service. Zero below the registration threshold. */
  taxPaise: paise('tax_paise').notNull().default(0n),
  taxRateBps: integer('tax_rate_bps').notNull().default(0),
  totalPaise: paise('total_paise').notNull().default(0n),

  commissionBps: integer('commission_bps').notNull().default(0),
  commissionPaise: paise('commission_paise').notNull().default(0n),
  /** GST on our commission, owed regardless of the shop's registration. */
  commissionTaxPaise: paise('commission_tax_paise').notNull().default(0n),
  commissionTaxBps: integer('commission_tax_bps').notNull().default(0),
  shopPayablePaise: paise('shop_payable_paise').notNull().default(0n),

  /** The itemised breakdown exactly as rendered, including every modifier label. */
  priceSnapshot: jsonb('price_snapshot').$type<Record<string, unknown>>(),
  pricingVersion: text('pricing_version'),
  priceSnapshotAt: tstz('price_snapshot_at'),

  requiresQuote: boolean('requires_quote').notNull().default(false),
  quoteId: uuid('quote_id'),
  quoteReason: text('quote_reason'),

  isPaid: boolean('is_paid').notNull().default(false),
  paidAt: tstz('paid_at'),
  /** Cached for lists. `payments` is authoritative. */
  paymentState: paymentStateEnum('payment_state'),
  refundedPaise: paise('refunded_paise').notNull().default(0n),
  /** Set when funds enter the shop's payable balance — on collection, never before. */
  fundsReleasedAt: tstz('funds_released_at'),
  /** FK added in migration 0007. */
  payoutId: uuid('payout_id'),

  placedAt: tstz('placed_at'),
  acceptDeadlineAt: tstz('accept_deadline_at'),
  acceptedAt: tstz('accepted_at'),
  acceptedBy: uuid('accepted_by').references(() => users.id),
  printingStartedAt: tstz('printing_started_at'),
  /** Computed from the shop's *open* hours, so a shop is not late for time it was shut. */
  readyPromisedAt: tstz('ready_promised_at'),
  readyAt: tstz('ready_at'),
  readyByUserId: uuid('ready_by_user_id').references(() => users.id),
  pickupDeadlineAt: tstz('pickup_deadline_at'),
  collectedAt: tstz('collected_at'),
  settledAt: tstz('settled_at'),
  cancelledAt: tstz('cancelled_at'),
  rejectedAt: tstz('rejected_at'),
  closedAt: tstz('closed_at'),

  /** Keyed hash for comparison. Never plaintext. */
  pickupCodeHash: text('pickup_code_hash'),
  pickupCodeEncrypted: text('pickup_code_encrypted'),
  /** Opaque; carries no order id and grants nothing without a shop session for this shop. */
  pickupQrSlug: text('pickup_qr_slug'),
  pickupCodeIssuedAt: tstz('pickup_code_issued_at'),
  pickupCodeSentCount: integer('pickup_code_sent_count').notNull().default(0),
  pickupFailedAttempts: integer('pickup_failed_attempts').notNull().default(0),
  pickupLockedUntil: tstz('pickup_locked_until'),
  pickupVerifiedAt: tstz('pickup_verified_at'),
  pickupVerifiedBy: uuid('pickup_verified_by').references(() => users.id),
  pickupMethod: text('pickup_method').$type<'code' | 'qr' | 'admin_override' | 'shop_override'>(),

  /** Customer instructions are customer content: encrypted at rest. */
  customerNoteEncrypted: text('customer_note_encrypted'),
  /** Not shown to the customer. */
  shopInternalNote: text('shop_internal_note'),
  /** Shown to the customer: "printed on 80 gsm, we were out of 70". */
  shopMessageToCustomer: text('shop_message_to_customer'),

  /** Raised by an admin. Blocks automatic settlement until cleared. */
  adminHoldAt: tstz('admin_hold_at'),
  adminHoldReason: text('admin_hold_reason'),
  /** FK added in migration 0009. */
  disputeId: uuid('dispute_id'),
  /** Denormalised so the shop queue shows a badge without a join. */
  hasOpenDispute: boolean('has_open_dispute').notNull().default(false),

  source: text('source')
    .$type<'pwa' | 'web' | 'shop_counter' | 'admin' | 'api'>()
    .notNull()
    .default('pwa'),
  ...timestamps,
})

/**
 * Fully snapshotted line items. The catalogue item's code, name and unit are copied
 * in, so an admin renaming "A4 B&W" or a shop deleting the item cannot change what
 * an old receipt says; `serviceItemId` survives for analytics only.
 *
 * `lineTotalPaise` is a pure function of the snapshot and is checked as such — if
 * the pricing engine has a bug, the INSERT fails rather than the order being wrong.
 */
export const orderItems = pgTable('order_items', {
  id: id(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  /** Finishing lines point at the print line they apply to, and are removed with it. */
  appliesToItemId: uuid('applies_to_item_id').references((): AnyPgColumn => orderItems.id, {
    onDelete: 'cascade',
  }),
  fileId: uuid('file_id').references(() => files.id, { onDelete: 'set null' }),
  serviceItemId: uuid('service_item_id').references(() => serviceItems.id, {
    onDelete: 'set null',
  }),
  sortOrder: integer('sort_order').notNull().default(0),

  itemCode: text('item_code').notNull(),
  itemName: text('item_name').notNull(),
  itemKind: text('item_kind').$type<'print' | 'finishing' | 'scan' | 'handling'>().notNull(),
  priceUnit: text('price_unit')
    .$type<'per_page' | 'per_sheet' | 'per_copy' | 'per_order' | 'per_sqft'>()
    .notNull(),
  paperSizeCode: text('paper_size_code'),
  colourMode: text('colour_mode').$type<'bw' | 'colour'>(),
  sides: text('sides').$type<'single' | 'double'>(),

  copies: integer('copies').notNull().default(1),
  /** As the customer typed it: '1-4, 9, 20-'. */
  pageRange: text('page_range'),
  pagesSelected: integer('pages_selected').notNull().default(0),
  colourPagesSelected: integer('colour_pages_selected'),
  sheets: integer('sheets').notNull().default(0),

  /** Expressed in `priceUnit` terms: pages, sheets, copies, or 1. */
  quantity: integer('quantity').notNull(),
  unitPricePaise: paise('unit_price_paise').notNull(),
  bandLabel: text('band_label'),
  bandMinQuantity: integer('band_min_quantity'),
  bandMaxQuantity: integer('band_max_quantity'),
  setupFeePaise: paise('setup_fee_paise').notNull().default(0n),
  /** Itemised, so the customer sees why a 2-page job cost ₹5 (FR-315). */
  minChargeTopupPaise: paise('min_charge_topup_paise').notNull().default(0n),
  discountPaise: paise('discount_paise').notNull().default(0n),
  lineTotalPaise: paise('line_total_paise').notNull(),

  note: text('note'),
  ...timestamps,
})

/**
 * Append-only. Audit trail, customer timeline and durable SSE outbox in one table on
 * purpose: if the timeline the customer sees and the trail an investigator reads
 * could diverge, one of them would be wrong.
 *
 * `metadata` is redacted on the way in — never file names, never pickup codes.
 */
export const orderEvents = pgTable('order_events', {
  id: id(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  /** Gapless per order, which is what makes Last-Event-ID replay exactly-once. */
  sequence: bigintCount('sequence').notNull(),
  event: text('event').notNull(),
  fromState: orderStateEnum('from_state'),
  toState: orderStateEnum('to_state'),

  /** Distinguishes a shop clicking Accept from a worker sweep and from a webhook. */
  actorType: text('actor_type')
    .$type<'customer' | 'shop' | 'admin' | 'system' | 'provider'>()
    .notNull(),
  actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
  actorRole: userRoleEnum('actor_role'),
  actorShopId: uuid('actor_shop_id').references(() => shops.id, { onDelete: 'set null' }),

  /** Machine-readable cause: 'accept_window_expired', 'file_unreadable'. */
  reasonCode: text('reason_code'),
  /** Human sentence, shown to the customer when `isCustomerVisible`. */
  message: text('message'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),

  isCustomerVisible: boolean('is_customer_visible').notNull().default(false),
  isShopVisible: boolean('is_shop_visible').notNull().default(false),

  /** Set for provider-driven events so a webhook redelivery cannot append a duplicate. */
  idempotencyKey: text('idempotency_key'),
  correlationId: text('correlation_id'),
  ...createdAt,
})

/**
 * For jobs that cannot be auto-priced: an unusual format, a DOCX whose page count we
 * will not guess at, a 400-page binding job. The shop proposes, the customer
 * accepts, and only then is the order payable (FR-306, FR-330).
 */
export const quotes = pgTable('quotes', {
  id: id(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  shopId: uuid('shop_id')
    .notNull()
    .references(() => shops.id, { onDelete: 'cascade' }),
  /** Sequential within the order: a shop may revise after a conversation. */
  revision: integer('revision').notNull().default(1),
  state: text('state')
    .$type<'draft' | 'sent' | 'accepted' | 'rejected' | 'expired' | 'withdrawn' | 'superseded'>()
    .notNull()
    .default('draft'),

  /** Same shape as orderItems; applied verbatim on acceptance. */
  proposedItems: jsonb('proposed_items').$type<Record<string, unknown>[]>().notNull(),
  itemsSubtotalPaise: paise('items_subtotal_paise').notNull(),
  discountPaise: paise('discount_paise').notNull().default(0n),
  surchargePaise: paise('surcharge_paise').notNull().default(0n),
  taxPaise: paise('tax_paise').notNull().default(0n),
  taxRateBps: integer('tax_rate_bps').notNull().default(0),
  totalPaise: paise('total_paise').notNull(),
  /** The turnaround the shop commits to if this quote is accepted. */
  turnaroundMinutes: integer('turnaround_minutes'),

  shopMessage: text('shop_message'),
  customerRequestNote: text('customer_request_note'),

  preparedBy: uuid('prepared_by').references(() => users.id),
  sentAt: tstz('sent_at'),
  /** Quotes expire: a price for a 300-page job is not good for a week. */
  expiresAt: tstz('expires_at'),
  respondedAt: tstz('responded_at'),
  acceptedAt: tstz('accepted_at'),
  rejectedAt: tstz('rejected_at'),
  rejectionReason: text('rejection_reason'),
  withdrawnAt: tstz('withdrawn_at'),
  ...timestamps,
})

/**
 * Append-only. Every attempt to collect an order, successful or not. A brute-force
 * run at a 6-character code is visible here, and `orders.pickupFailedAttempts` locks
 * it out (FR-427, NFR-14).
 */
export const pickupVerifications = pgTable('pickup_verifications', {
  id: id(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  shopId: uuid('shop_id')
    .notNull()
    .references(() => shops.id, { onDelete: 'cascade' }),
  method: text('method').$type<'code' | 'qr' | 'shop_override' | 'admin_override'>().notNull(),
  outcome: text('outcome')
    .$type<'success' | 'wrong_code' | 'expired' | 'locked' | 'wrong_state' | 'wrong_shop' | 'override'>()
    .notNull(),
  /** Hash of what was presented, so a repeated wrong code is recognisable. */
  presentedHash: text('presented_hash'),
  failureReason: text('failure_reason'),
  /** Required for an override, and surfaced in the trust queue. */
  overrideReason: text('override_reason'),
  verifiedBy: uuid('verified_by').references(() => users.id, { onDelete: 'set null' }),
  actorRole: userRoleEnum('actor_role'),
  ipHash: text('ip_hash'),
  ...createdAt,
})

/**
 * The shop opens the file and it is a scan of a scan, or a 900-page book they cannot
 * bind. The order pauses instead of failing: the customer is asked for a replacement
 * and the SLA clock stops (FR-418). An unanswered hold cancels with a full refund.
 */
export const orderHolds = pgTable('order_holds', {
  id: id(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  fileId: uuid('file_id').references(() => files.id, { onDelete: 'set null' }),
  reasonCode: text('reason_code')
    .$type<
      | 'unreadable_file'
      | 'wrong_page_count'
      | 'password_protected'
      | 'unsupported_format'
      | 'too_large_for_shop'
      | 'colour_mismatch'
      | 'paper_unavailable'
      | 'finishing_impossible'
      | 'customer_clarification'
      | 'other'
    >()
    .notNull(),
  /** Shop-authored from a template, so it is never just "file bad". */
  messageToCustomer: text('message_to_customer').notNull(),
  raisedBy: uuid('raised_by').references(() => users.id),
  raisedAt: tstz('raised_at').notNull().defaultNow(),
  /** The state to restore when the hold resolves. */
  stateBefore: orderStateEnum('state_before').notNull(),
  /** SLA credit: minutes the clock was stopped, added back to the promise. */
  pausedMinutes: integer('paused_minutes'),
  resolution: text('resolution').$type<
    'file_replaced' | 'customer_confirmed' | 'reconfigured' | 'cancelled_refund' | 'shop_proceeded' | 'expired'
  >(),
  replacementFileId: uuid('replacement_file_id').references(() => files.id, {
    onDelete: 'set null',
  }),
  resolvedAt: tstz('resolved_at'),
  resolvedBy: uuid('resolved_by').references(() => users.id),
  expiresAt: tstz('expires_at').notNull(),
  ...timestamps,
})

/**
 * One row per cancellation, recording the refund policy applied *and its version*.
 * When a customer asks in six months why they got 100% back and their friend got
 * nothing, the answer is here (PRD §39.3).
 */
export const orderCancellations = pgTable('order_cancellations', {
  id: id(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  cancelledByUserId: uuid('cancelled_by_user_id').references(() => users.id, {
    onDelete: 'set null',
  }),
  actorType: text('actor_type').$type<'customer' | 'shop' | 'admin' | 'system'>().notNull(),
  stateAtCancellation: orderStateEnum('state_at_cancellation').notNull(),
  reasonCode: text('reason_code')
    .$type<
      | 'customer_changed_mind'
      | 'customer_wrong_file'
      | 'customer_found_elsewhere'
      | 'shop_too_busy'
      | 'shop_cannot_print'
      | 'shop_closed'
      | 'shop_equipment_down'
      | 'accept_window_expired'
      | 'payment_failed'
      | 'hold_unresolved'
      | 'pickup_window_expired'
      | 'admin_intervention'
      | 'fraud_suspected'
      | 'other'
    >()
    .notNull(),
  reasonText: text('reason_text'),
  refundRateBps: integer('refund_rate_bps').notNull(),
  refundPaise: paise('refund_paise').notNull(),
  policyVersion: text('policy_version').notNull(),
  policyExplanation: text('policy_explanation').notNull(),
  /** Whether this counts against the shop's acceptance rate. */
  countsAgainstShop: boolean('counts_against_shop').notNull().default(false),
  ...createdAt,
})

/**
 * Only a collected order can be rated, so a rating is always attached to a real
 * transaction. That one rule removes most review spam without a moderation team
 * (FR-701) — and it is enforced by trigger, not by convention.
 */
export const orderRatings = pgTable('order_ratings', {
  id: id(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  shopId: uuid('shop_id')
    .notNull()
    .references(() => shops.id, { onDelete: 'cascade' }),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  stars: smallint('stars').notNull(),
  /** Structured feedback, so "3 people mentioned print quality" needs no NLP. */
  tags: text('tags').array().notNull().default([]),
  comment: text('comment'),
  isPublic: boolean('is_public').notNull().default(true),
  moderationState: text('moderation_state')
    .$type<'published' | 'pending_review' | 'hidden' | 'removed'>()
    .notNull()
    .default('published'),
  moderatedBy: uuid('moderated_by').references(() => users.id),
  moderatedAt: tstz('moderated_at'),
  moderationReason: text('moderation_reason'),
  /** The shop's one reply. */
  shopReply: text('shop_reply'),
  shopRepliedAt: tstz('shop_replied_at'),
  ...timestamps,
})
