/**
 * Column helpers shared by every schema module.
 *
 * The SQL migrations in `db/migrations` are the source of truth for the schema.
 * These definitions exist so the application gets types and a query builder over
 * that schema, and `schema-parity.itest.ts` asserts the two never drift.
 */

import { bigint, customType, timestamp, uuid } from 'drizzle-orm/pg-core'

/**
 * Case-insensitive text. Used for anything a human types and expects to match
 * regardless of case: emails, slugs, service codes, config keys.
 */
export const citext = customType<{ data: string; driverData: string }>({
  dataType() {
    return 'citext'
  },
})

/**
 * A PostGIS point in WGS 84.
 *
 * Deliberately typed as an opaque string: what Postgres returns is EWKB hex, and
 * writing a point requires `ST_SetSRID(ST_MakePoint(...))`, which a column type
 * cannot express. Every read that needs coordinates and every write goes through
 * explicit SQL in the discovery repository, where the spatial predicate lives
 * anyway. Declaring it here means the parity test can see the column; it does not
 * mean you should select it directly.
 */
export const geographyPoint = customType<{ data: string; driverData: string }>({
  dataType() {
    return 'geography(Point,4326)'
  },
})

/**
 * Money. Always integer paise, never a float, never a decimal string that some
 * other layer might parse with `parseFloat`.
 *
 * `mode: 'bigint'` lines the column up with `Paise` from `src/lib/money.ts`, so a
 * value read from the database and a value produced by the pricing engine are the
 * same type and cannot be added to a rupee number by accident.
 */
export const paise = (name: string) => bigint(name, { mode: 'bigint' })

/** A plain `bigint` that is a counter rather than an amount (sequences, byte sizes). */
export const bigintCount = (name: string) => bigint(name, { mode: 'bigint' })

/** `timestamptz`. Every timestamp in Chaapo is absolute; IST is a display concern. */
export const tstz = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' })

/**
 * The standard primary key. Generated by `newId()` in the application, never by a
 * database default, because the domain layer needs the id before insert so that an
 * audit row and an outbox row can be written in the same transaction.
 */
export const id = () => uuid('id').primaryKey()

/** `created_at` / `updated_at`, maintained by the `set_updated_at()` trigger. */
export const timestamps = {
  createdAt: tstz('created_at').notNull().defaultNow(),
  updatedAt: tstz('updated_at').notNull().defaultNow(),
}

/** Just `created_at`, for append-only tables that are never updated. */
export const createdAt = {
  createdAt: tstz('created_at').notNull().defaultNow(),
}

/** Soft-delete marker. Present only where the PRD requires recoverability. */
export const softDelete = {
  deletedAt: tstz('deleted_at'),
}
